### PR TITLE
Add Jupyter Book documentation

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Note: this PR also removes the check version action but adds some documentation. I won't merge before your OK, @anth-volk! Happy to put back in if you have strong thoughts.

### CODE REVIEW

**Comment by anth-volk** [comment]
@nikhilwoodruff Just curious - why remove? Is it because of #51? Because when I previously added commits, typically the versioning PR just didn't rerun the tests at all, but curious to hear what's going on with that.

**Comment by nikhilwoodruff** [comment]
@anth-volk e.g. [this PR](https://github.com/PolicyEngine/policyengine-us-data/pull/35) has the check version failing every time.

**Comment by anth-volk** [comment]
@nikhilwoodruff I see what's going on here. The script to generate the changelog consumes the `changelog_entry.yaml` file, such that on subsequent action runs, it's missing and no longer possible to generate the log. Yeah, probably best to dump for the time being and find a better way of managing, and then if we come across any `pip install` errors in downstream packages, bear in mind it could be version number-related.

**Comment by nikhilwoodruff** [comment]
@anth-volk thanks!

**Pull request merged**
