### PR TITLE
Bump to policyengine-us 1.100.0

### LINKED ISSUE #80: Fix string loading for pooled 3-year CPS dataset
Error reported by @PavelMakarchuk:

image

### LINKED ISSUE #88: Bump to policyengine-us 1.100.0

### LINKED ISSUE #92: Large negative incomes in household market income
This doesn't seem to affect budgetary impacts significantly, but the 3m households with negative incomes have very large (10tr) negative incomes that don't filter through to IRS gross income or AGI (these households are effectively zero income records).

The PUF has 2.5m negative income households with 138bn in total household market income: I think we should target to 3m and 138bn for negative household market income.

### PR DESCRIPTION
**Pull request by MaxGhenis**
Fix #88
Fix #80
Fix #92

### CODE REVIEW

**Comment by MaxGhenis** [comment]
@nikhilwoodruff could you take a look at this? Can't download the PUF.

https://github.com/PolicyEngine/policyengine-us-data/actions/runs/11080393076/job/30791143720#step:6:197

**Comment by nikhilwoodruff** [comment]
Fixes #80 
Fixes #92

**Comment by nikhilwoodruff** [comment]
The PUF failed to download because we added a URL for it, prompting the data generation script to try to download it. But that stage of the action doesn't pass through the GitHub token needed to download it. Fixed by adding a manually specified step to create the PUF dataset.

**Comment by nikhilwoodruff** [comment]
Fix #69 
Also set the datasets to point to a new release, that I'll create on merge. I can't pre-create it beforehand because then the push action will fail to create it. We should automate this process but it'll probably require some time-intensive trial and error and I'd like to just get this in today.

**Comment by nikhilwoodruff** [comment]
Adding a 'lite mode' to the tests so they only generate a 10k subset of the ECPS. Also removed the auto-upload since this will produce imperfect datasets. We need to find a solution to GitHub OOM Killed-ing the workers, but for now it means we can't autogenerate datasets in GH actions

**Pull request merged**
